### ISSUE TITLE
Components and PCB

### ISSUE THREAD

**Issue by conaito** [positron96/LocoNetControlStation#3]
I was happy to find your product and idea. its exactly what i looking for. Well, the problem is to getting the hardware.. PCB no problem but SMD parts looks like not longer available. I sthere any chance to can get updated BPM and PickandPlace files (as best for jlcpcb)? I really would build it

**Comment by positron96** [comment]
Hi, what exactly can't you find? I'm sure the components are widely available.

**Comment by conaito** [comment]
i would order the pcb with already SMD parts soldered on jlcpcb website and
need a pick and place file + bom file for it. can you may send it to me?
all what i try i get many parts not available there (looks like the BOM is
not up to date)?

Am Do., 4. Feb. 2021 um 15:05 Uhr schrieb Pavel Melnikov <
notifications@github.com>:

**Comment by conaito** [comment]
may the best would be if you can give a idea do connect all with the breakoztboard and usingyiur code instead of order pcb and solder all the parts? is that possible? i really think your solution is exactly what i looking for since long time
Am 4. Feb. 2021, 15:05 +0100 schrieb Pavel Melnikov <notifications@github.com>:

**Comment by positron96** [comment]
Hello. I've tried to order BOM via LCSC and yes, it looks like a lot of components are discontinued, but actually, they are fine, LCSC just does not know what to look for. This is because LCSC IDs are missing from my schematic and I have no idea how to tell LCSC what elements are what. If you want to order from LCSC, I'm afraid you'd need to search LCSC for required components (e.g. look for SMD resistor of 10kOhm with package 0805). The best way may be to open the schematic from here https://oshwlab.com/positron96/loconet-command-station, go to File -> Export BOM and assign the needed LCSC IDs to items that lack it.

**Comment by conaito** [comment]
i will try it. can you may send me a breakout board connection diagramm? its maybe morebetter to full understand it.
Am 5. Feb. 2021, 08:57 +0100 schrieb Pavel Melnikov <notifications@github.com>:

**Comment by positron96** [comment]
Before ordering a PCB, I've tested the circuit on a solderless breadboard. You can do it as well, yes, just take through-hole variants of resistors, capacitors and ICs. The schematic shows what connects to what (it's better than breadboard diagram, believe me!) 

On large scale, there 2 parts of the board - loconet decoder/encoder and DCC generation/sensing.
For Loconet, you can take simplest implementation from mrwa: https://mrrwa.org/loconet-interface/,
To save time, for DCC you can also use a pre-made L298 board instead of making it from scratch. You need the one with current sense pins broken out, like this: https://aliexpress.ru/item/32902216756.html?sellermenu_hide=true&src=googleweb&albch=srch&albcp=12196898613&aff_short_key=_bXebKgA&isdl=y&aff_platform=jvru&tracelog=googleweb_jvru_mbag_3126936_cl3_loucoster_0&campaignName=JVRU_CM_ALI_WEBall_RU_UA_sTRADE_CL3_LOUCOSTER_0_Perform&albag=333333333333&albad=444444444444&albagn=mbag&acnt=1330229468&_1ld=3126936_1&utm_medium=cpc&utm_source=google&utm_campaign=JVRU_CM_ALI_WEBall_RU_UA_sTRADE_CL3_LOUCOSTER_0_Perform&gclid=CjwKCAiA9vOABhBfEiwATCi7GPvPlLviUY71cs-KItVEYUsN1osxewnUPK0Z1nX32GLLU-C_5f-mbRoCLQwQAvD_BwE&sku_id=65782883924. The hex invertor can be replaced with 2 transistors for simplicity.

Also, you might want to replace Lolin32 Lite with esp32 DevC board, then you won't need 3.3V regulator and filtering capacitors as DevC esp32 board already has them.

**Comment by conaito** [comment]
can you give me a idea about the replace of hex inverter? how exactly and where i must do it on the ready L298 board?

Flying regards,
Attila
Am 5. Feb. 2021, 09:18 +0100 schrieb Pavel Melnikov <notifications@github.com>:

**Comment by positron96** [comment]
Hi. A simple invertor can be made with one transistor (and some resistors): https://en.wikipedia.org/wiki/Inverter_(logic_gate)

As to where to put it, an L298 needs 2 wires to control one DCC track. As per DCC standard, the signals on these wires must be of opposite voltage, hence you need an invertor to invert one signal into its opposite. That one signal is coming from ESP32 board.

You could actually work without an invertor, but you need to generate both signals on an MCU. Totally doable, but requires changing the firmware.

**Comment by conaito** [comment]
so it must attach on the outputs between the track not on the L298 board itself soldered (or parts replaced)?

Flying regards,
Attila
Am 13. Feb. 2021, 07:07 +0100 schrieb Pavel Melnikov <notifications@github.com>:

**Comment by positron96** [comment]
Yes, L298 board should be left intact
